#! /bin/bash
# /etc/init.d/garagerelay

case "$1" in
  start)
    echo "Starting Relay"
    # Turn 0 off
    /usr/local/bin/gpio write 0 0
    #Start Gpio
    /usr/local/bin/gpio mode 0 out
  ;;
  stop)
    echo "Stopping gpio"
  ;;
  *)
    echo "Usage: /etc/init.d/garagerelay {start|stop}"
    exit 1
    ;;
  esac
exit 0
