#! /bin/bash
# /etc/init.d/garage-pi

export SERVER_DIR=$GOPATH/src/github.com/robdimsdale/garage-pi

case "$1" in 
  start)
    echo "Starting garage-pi"
    go run garage-pi 1> "$SERVER_DIR/out.log" 2>"$SERVER_DIR/err.log" &
    ;;
  stop)
    echo "Stopping garage-pi"
    killall go
    ;;
  *)
    echo "Usage: /etc/init.d/garage-pi {start|stop}"
    exit 1
    ;;
  esac
exit 0
