#! /bin/bash
# /etc/init.d/garage-pi

GOPATH=/go
PATH=$GOPATH/bin:$PATH

export SERVER_DIR=$GOPATH/src/github.com/robdimsdale/garage-pi

case "$1" in 
  start)
    echo "Starting garage-pi"
    cd $SERVER_DIR
    garage-pi 1>out.log 2>out.log &
    ;;
  stop)
    echo "Stopping garage-pi"
    killall garage-pi
    ;;
  *)
    echo "Usage: /etc/init.d/garage-pi {start|stop}"
    exit 1
    ;;
  esac
exit 0
