#!/bin/bash

set -eux

root_dir="$PWD"
garagepi_bin_path="$(ls "${root_dir}"/candidate-release-linux/garagepi-*)"
export garagepi_bin_path
chmod +x "${garagepi_bin_path}"

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects that it lives two directories below the base directory.
base_dir="$( cd "${my_dir}/../.." && pwd )"

# And that scripts/ lives one directory below the base directory.
scripts_dir="$( cd "${base_dir}/scripts/" && pwd )"

go get \
  github.com/onsi/ginkgo/ginkgo \
  github.com/onsi/gomega

"${scripts_dir}"/smoke-tests
