#!/bin/bash

set -eux

ROOT="$PWD"
VERSION="$(cat version/number)"

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects that it lives two directories below the base directory.
BASE_DIR="$( cd ${MY_DIR}/../.. && pwd )"

pushd ${BASE_DIR}
  mkdir -p $GOPATH/src/github.com/robdimsdale
  ln -s $PWD $GOPATH/src/github.com/robdimsdale/garagepi

  go get github.com/tools/godep

  godep restore

  IFS='-' read -ra arrVERSION <<< "${VERSION}"
  stripped_version="${arrVERSION[0]}"

  go build \
    -o "${ROOT}"/garagepi-"${VERSION}" \
    -ldflags "-X main.version ${stripped_version}" \
    main.go
popd
