#!/bin/bash

set -eux

root_dir="$PWD"
PRIVATE_KEY="${PRIVATE_KEY:-deployments/pipelines/garagepi/concourse.private.key}"
chmod 600 "${PRIVATE_KEY}"

CANDIDATE_RELEASE="${CANDIDATE_RELEASE:-$(ls "${root_dir}"/candidate-release-arm/garagepi-arm-*)}"

TARGET_USER="${TARGET_USER:-pi}"
TARGET_HOST="${TARGET_HOST:?}"
TARGET_PORT="${TARGET_PORT:-22}"

ssh \
  -i "${PRIVATE_KEY}" \
  -o StrictHostKeyChecking=no \
  -p "${TARGET_PORT}" \
  "${TARGET_USER}@${TARGET_HOST}" \
  "sudo rm -f /tmp/garagepi"

scp \
  -i "${PRIVATE_KEY}" \
  -P "${TARGET_PORT}" \
  "${CANDIDATE_RELEASE}" \
  "${TARGET_USER}@${TARGET_HOST}":/tmp/garagepi

ssh \
  -i "${PRIVATE_KEY}" \
  -p "${TARGET_PORT}" \
  "${TARGET_USER}@${TARGET_HOST}" \
  "sudo service garagepi stop && \
  cp /tmp/garagepi /go/bin/garagepi && \
  sudo rm -f /tmp/garagepi && \
  sudo service garagepi start"
