#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects that it lives two directories below the base directory.
BASE_DIR="$( cd ${MY_DIR}/../.. && pwd )"

# And that scripts/ lives one directory below the base directory.
SCRIPTS_DIR="$( cd ${BASE_DIR}/scripts/ && pwd )"

pushd ${BASE_DIR}
  go get -v github.com/onsi/ginkgo/ginkgo
  go get golang.org/x/tools/cmd/vet
  go get -v -t -d ./...
  go get github.com/tools/godep
  godep restore
popd

${SCRIPTS_DIR}/run_tests
