#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects that it lives two directories below the base directory.
BASE_DIR="$( cd ${MY_DIR}/../.. && pwd )"

# And that scripts/ lives one directory below the base directory.
SCRIPTS_DIR="$( cd ${BASE_DIR}/scripts/ && pwd )"

pushd ${BASE_DIR}
  mkdir -p $GOPATH/src/github.com/robdimsdale
  ln -s $PWD $GOPATH/src/github.com/robdimsdale/garagepi

  go get github.com/onsi/ginkgo/ginkgo
  go get golang.org/x/tools/cmd/vet
  go get github.com/tools/godep

  go get -v -t -d ./...
  godep restore

  ${SCRIPTS_DIR}/tests
popd
