// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/robdimsdale/garage-pi/logger"
)

type FakeLogger struct {
	LogStub        func(message string)
	logMutex       sync.RWMutex
	logArgsForCall []struct {
		message string
	}
}

func (fake *FakeLogger) Log(message string) {
	fake.logMutex.Lock()
	fake.logArgsForCall = append(fake.logArgsForCall, struct {
		message string
	}{message})
	fake.logMutex.Unlock()
	if fake.LogStub != nil {
		fake.LogStub(message)
	}
}

func (fake *FakeLogger) LogCallCount() int {
	fake.logMutex.RLock()
	defer fake.logMutex.RUnlock()
	return len(fake.logArgsForCall)
}

func (fake *FakeLogger) LogArgsForCall(i int) string {
	fake.logMutex.RLock()
	defer fake.logMutex.RUnlock()
	return fake.logArgsForCall[i].message
}

var _ logger.Logger = new(FakeLogger)
