// This file was generated by counterfeiter
package fakes

import (
	"net/http"
	"sync"
	"time"

	"github.com/robdimsdale/garagepi"
)

type FakeOsHelper struct {
	ExecStub        func(executable string, arg ...string) (string, error)
	execMutex       sync.RWMutex
	execArgsForCall []struct {
		executable string
		arg        []string
	}
	execReturns struct {
		result1 string
		result2 error
	}
	GetStaticFileSystemStub        func() (http.FileSystem, error)
	getStaticFileSystemMutex       sync.RWMutex
	getStaticFileSystemArgsForCall []struct{}
	getStaticFileSystemReturns     struct {
		result1 http.FileSystem
		result2 error
	}
	GetHomepageTemplateContentsStub        func() ([]byte, error)
	getHomepageTemplateContentsMutex       sync.RWMutex
	getHomepageTemplateContentsArgsForCall []struct{}
	getHomepageTemplateContentsReturns     struct {
		result1 []byte
		result2 error
	}
	SleepStub        func(d time.Duration)
	sleepMutex       sync.RWMutex
	sleepArgsForCall []struct {
		d time.Duration
	}
}

func (fake *FakeOsHelper) Exec(executable string, arg ...string) (string, error) {
	fake.execMutex.Lock()
	fake.execArgsForCall = append(fake.execArgsForCall, struct {
		executable string
		arg        []string
	}{executable, arg})
	fake.execMutex.Unlock()
	if fake.ExecStub != nil {
		return fake.ExecStub(executable, arg...)
	} else {
		return fake.execReturns.result1, fake.execReturns.result2
	}
}

func (fake *FakeOsHelper) ExecCallCount() int {
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	return len(fake.execArgsForCall)
}

func (fake *FakeOsHelper) ExecArgsForCall(i int) (string, []string) {
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	return fake.execArgsForCall[i].executable, fake.execArgsForCall[i].arg
}

func (fake *FakeOsHelper) ExecReturns(result1 string, result2 error) {
	fake.ExecStub = nil
	fake.execReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeOsHelper) GetStaticFileSystem() (http.FileSystem, error) {
	fake.getStaticFileSystemMutex.Lock()
	fake.getStaticFileSystemArgsForCall = append(fake.getStaticFileSystemArgsForCall, struct{}{})
	fake.getStaticFileSystemMutex.Unlock()
	if fake.GetStaticFileSystemStub != nil {
		return fake.GetStaticFileSystemStub()
	} else {
		return fake.getStaticFileSystemReturns.result1, fake.getStaticFileSystemReturns.result2
	}
}

func (fake *FakeOsHelper) GetStaticFileSystemCallCount() int {
	fake.getStaticFileSystemMutex.RLock()
	defer fake.getStaticFileSystemMutex.RUnlock()
	return len(fake.getStaticFileSystemArgsForCall)
}

func (fake *FakeOsHelper) GetStaticFileSystemReturns(result1 http.FileSystem, result2 error) {
	fake.GetStaticFileSystemStub = nil
	fake.getStaticFileSystemReturns = struct {
		result1 http.FileSystem
		result2 error
	}{result1, result2}
}

func (fake *FakeOsHelper) GetHomepageTemplateContents() ([]byte, error) {
	fake.getHomepageTemplateContentsMutex.Lock()
	fake.getHomepageTemplateContentsArgsForCall = append(fake.getHomepageTemplateContentsArgsForCall, struct{}{})
	fake.getHomepageTemplateContentsMutex.Unlock()
	if fake.GetHomepageTemplateContentsStub != nil {
		return fake.GetHomepageTemplateContentsStub()
	} else {
		return fake.getHomepageTemplateContentsReturns.result1, fake.getHomepageTemplateContentsReturns.result2
	}
}

func (fake *FakeOsHelper) GetHomepageTemplateContentsCallCount() int {
	fake.getHomepageTemplateContentsMutex.RLock()
	defer fake.getHomepageTemplateContentsMutex.RUnlock()
	return len(fake.getHomepageTemplateContentsArgsForCall)
}

func (fake *FakeOsHelper) GetHomepageTemplateContentsReturns(result1 []byte, result2 error) {
	fake.GetHomepageTemplateContentsStub = nil
	fake.getHomepageTemplateContentsReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeOsHelper) Sleep(d time.Duration) {
	fake.sleepMutex.Lock()
	fake.sleepArgsForCall = append(fake.sleepArgsForCall, struct {
		d time.Duration
	}{d})
	fake.sleepMutex.Unlock()
	if fake.SleepStub != nil {
		fake.SleepStub(d)
	}
}

func (fake *FakeOsHelper) SleepCallCount() int {
	fake.sleepMutex.RLock()
	defer fake.sleepMutex.RUnlock()
	return len(fake.sleepArgsForCall)
}

func (fake *FakeOsHelper) SleepArgsForCall(i int) time.Duration {
	fake.sleepMutex.RLock()
	defer fake.sleepMutex.RUnlock()
	return fake.sleepArgsForCall[i].d
}

var _ garagepi.OsHelper = new(FakeOsHelper)
