// This file was generated by counterfeiter
package fakes

import (
	"net/http"
	"sync"

	"github.com/robdimsdale/garagepi"
)

type FakeFsHelper struct {
	GetStaticFileSystemStub        func() (http.FileSystem, error)
	getStaticFileSystemMutex       sync.RWMutex
	getStaticFileSystemArgsForCall []struct{}
	getStaticFileSystemReturns     struct {
		result1 http.FileSystem
		result2 error
	}
	GetHomepageTemplateContentsStub        func() ([]byte, error)
	getHomepageTemplateContentsMutex       sync.RWMutex
	getHomepageTemplateContentsArgsForCall []struct{}
	getHomepageTemplateContentsReturns     struct {
		result1 []byte
		result2 error
	}
}

func (fake *FakeFsHelper) GetStaticFileSystem() (http.FileSystem, error) {
	fake.getStaticFileSystemMutex.Lock()
	fake.getStaticFileSystemArgsForCall = append(fake.getStaticFileSystemArgsForCall, struct{}{})
	fake.getStaticFileSystemMutex.Unlock()
	if fake.GetStaticFileSystemStub != nil {
		return fake.GetStaticFileSystemStub()
	} else {
		return fake.getStaticFileSystemReturns.result1, fake.getStaticFileSystemReturns.result2
	}
}

func (fake *FakeFsHelper) GetStaticFileSystemCallCount() int {
	fake.getStaticFileSystemMutex.RLock()
	defer fake.getStaticFileSystemMutex.RUnlock()
	return len(fake.getStaticFileSystemArgsForCall)
}

func (fake *FakeFsHelper) GetStaticFileSystemReturns(result1 http.FileSystem, result2 error) {
	fake.GetStaticFileSystemStub = nil
	fake.getStaticFileSystemReturns = struct {
		result1 http.FileSystem
		result2 error
	}{result1, result2}
}

func (fake *FakeFsHelper) GetHomepageTemplateContents() ([]byte, error) {
	fake.getHomepageTemplateContentsMutex.Lock()
	fake.getHomepageTemplateContentsArgsForCall = append(fake.getHomepageTemplateContentsArgsForCall, struct{}{})
	fake.getHomepageTemplateContentsMutex.Unlock()
	if fake.GetHomepageTemplateContentsStub != nil {
		return fake.GetHomepageTemplateContentsStub()
	} else {
		return fake.getHomepageTemplateContentsReturns.result1, fake.getHomepageTemplateContentsReturns.result2
	}
}

func (fake *FakeFsHelper) GetHomepageTemplateContentsCallCount() int {
	fake.getHomepageTemplateContentsMutex.RLock()
	defer fake.getHomepageTemplateContentsMutex.RUnlock()
	return len(fake.getHomepageTemplateContentsArgsForCall)
}

func (fake *FakeFsHelper) GetHomepageTemplateContentsReturns(result1 []byte, result2 error) {
	fake.GetHomepageTemplateContentsStub = nil
	fake.getHomepageTemplateContentsReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

var _ garagepi.FsHelper = new(FakeFsHelper)
