// This file was generated by counterfeiter
package fakes

import (
	"net/http"
	"sync"

	"github.com/robdimsdale/garagepi/api/door"
)

type FakeHandler struct {
	HandleToggleStub        func(w http.ResponseWriter, r *http.Request)
	handleToggleMutex       sync.RWMutex
	handleToggleArgsForCall []struct {
		w http.ResponseWriter
		r *http.Request
	}
}

func (fake *FakeHandler) HandleToggle(w http.ResponseWriter, r *http.Request) {
	fake.handleToggleMutex.Lock()
	fake.handleToggleArgsForCall = append(fake.handleToggleArgsForCall, struct {
		w http.ResponseWriter
		r *http.Request
	}{w, r})
	fake.handleToggleMutex.Unlock()
	if fake.HandleToggleStub != nil {
		fake.HandleToggleStub(w, r)
	}
}

func (fake *FakeHandler) HandleToggleCallCount() int {
	fake.handleToggleMutex.RLock()
	defer fake.handleToggleMutex.RUnlock()
	return len(fake.handleToggleArgsForCall)
}

func (fake *FakeHandler) HandleToggleArgsForCall(i int) (http.ResponseWriter, *http.Request) {
	fake.handleToggleMutex.RLock()
	defer fake.handleToggleMutex.RUnlock()
	return fake.handleToggleArgsForCall[i].w, fake.handleToggleArgsForCall[i].r
}

var _ door.Handler = new(FakeHandler)
