#!/bin/bash

set -eu

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects that it lives one directory below the base directory.
base_dir="$( cd "${my_dir}/.." && pwd )"

pushd "${base_dir}"
  esc \
    -pkg=templates \
    -prefix web/assets \
    -o ./web/templates/fs.go \
    ./web/assets/templates/

  esc \
    -pkg=static \
    -prefix web/assets \
    -o ./web/static/fs.go \
    ./web/assets/static/
popd

echo "All embedded assets created successfully"
