#!/bin/bash

set -eux

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects that it lives one directory below the base directory.
base_dir="$( cd "${my_dir}/.." && pwd )"

pushd "${base_dir}"
  if [ "$#" != "0" ]; then
    ids=""
    for id in "$@"; do
      ids="$ids #${id}"
    done
  fi

  echo "[finishes${ids}]" | git ci --file -
  
  git ci --amend
popd
