#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects that it lives one directory below the base directory.
BASE_DIR="$( cd ${MY_DIR}/.. && pwd )"

pushd ${BASE_DIR}
  ginkgo \
    -p \
    -race \
    -randomizeAllSpecs \
    "$@" \
    integration_test

  ginkgo \
    -p \
    -r \
    -randomizeAllSpecs \
    "$@" \
    integration_test/ui
popd
