#!/bin/bash

set -eux

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects that it lives one directory below the base directory.
base_dir="$( cd "${my_dir}/.." && pwd )"

pushd "${base_dir}"
  ginkgo \
    -p \
    -race \
    -randomizeAllSpecs \
    "$@" \
    integration_test

  ginkgo \
    -p \
    -r \
    -randomizeAllSpecs \
    "$@" \
    integration_test/ui
popd
