#!/bin/bash

set -eux

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects that it lives one directory below the base directory.
base_dir="$( cd "${my_dir}/.." && pwd )"

pushd "${base_dir}"
  ginkgo \
    -p \
    -r \
    -race \
    -randomizeAllSpecs \
    -randomizeSuites \
    -skipPackage="integration_test,smoke_test" \
    "$@" \
    .
popd
