#! /bin/bash
# /etc/init.d/garagepi

OUT_LOG=/dev/null
GARAGEPI_BINARY=/go/bin/garagepi
HTTP_PORT=9999
HTTPS_PORT=19999
WEBCAM_HOST=localhost
WEBCAM_PORT=8080
ENABLE_HTTPS=false
FORCE_HTTPS=false
KEY_FILE=
CERT_FILE=
LOG_LEVEL=info
USERNAME=
PASSWORD=

start() {
    echo "Starting garagepi"
    $GARAGEPI_BINARY \
      -httpPort=$HTTP_PORT \
      -httpsPort=$HTTPS_PORT \
      -webcamHost=$WEBCAM_HOST \
      -webcamPort=$WEBCAM_PORT \
      -enableHTTPS=$ENABLE_HTTPS \
      -forceHTTPS=$FORCE_HTTPS \
      -keyFile=$KEY_FILE \
      -certFile=$CERT_FILE \
      -logLevel=$LOG_LEVEL \
      -username=$USERNAME \
      -password=$PASSWORD \
      2>&1 | tee $OUT_LOG | logger -t garagepi &
}

stop() {
    echo "Stopping garagepi"
    killall -w -q $GARAGEPI_BINARY
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop && start
    ;;
  *)
    echo "Usage: /etc/init.d/garagepi {start|stop|restart}"
    exit 1
    ;;
  esac
exit 0
