#! /bin/bash
# /etc/init.d/garagepi

OUT_LOG=/dev/null
GARAGEPI_BINARY=/go/bin/garagepi
PID_FILE=/run/garagepi.pid
HTTP_PORT=9999
HTTPS_PORT=19999
WEBCAM_HOST=localhost
WEBCAM_PORT=8080
ENABLE_HTTPS=false
FORCE_HTTPS=false
KEY_FILE=
CERT_FILE=
LOG_LEVEL=info
USERNAME=
PASSWORD=

start() {
    pid_guard

    echo "Starting garagepi"
    "${GARAGEPI_BINARY}" \
      -pidFile="${PID_FILE}" \
      -httpPort="${HTTP_PORT}" \
      -httpsPort="${HTTPS_PORT}" \
      -webcamHost="${WEBCAM_HOST}" \
      -webcamPort="${WEBCAM_PORT}" \
      -enableHTTPS="${ENABLE_HTTPS}" \
      -forceHTTPS="${FORCE_HTTPS}" \
      -keyFile="${KEY_FILE}" \
      -certFile="${CERT_FILE}" \
      -logLevel="${LOG_LEVEL}" \
      -username="${USERNAME}" \
      -password="${PASSWORD}" \
      2>&1 | tee "${OUT_LOG}" | logger -t garagepi &
}

pid_guard() {
  if [ -f "${PID_FILE}" ]; then
    pid=$(head -1 "${PID_FILE}")

    if [ -n "${pid}" ] && [ -e "/proc/${pid}" ]; then
      echo "garagepi is already running, please stop it first"
      exit 1
    fi

    echo "Removing stale pidfile..."
    rm "${PID_FILE}"
  fi
}

stop() {
    echo "Stopping garagepi"

    if [ -f "${PID_FILE}" ]; then
      pid=$(head -1 "${PID_FILE}")

      if [ -z "$pid" ]; then
        echo "Unable to get pid from ${PID_FILE}"
        exit 1
      fi

      if [ -e "/proc/${pid}" ]; then
        echo "Killing ${PID_FILE}: ${pid} "
        kill "${pid}"
        sleep 2
        if [ -e "/proc/${pid}" ]; then
          echo "Timed Out"
        else
          echo "Stopped"
        fi
      else
        echo "Process ${pid} is not running"
      fi

      rm -f "${PID_FILE}"
    else
      echo "Pidfile ${PID_FILE} doesn't exist"
    fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop && start
    ;;
  *)
    echo "Usage: /etc/init.d/garagepi {start|stop|restart}"
    exit 1
    ;;
  esac
exit 0
